### ISSUE TITLE
TTS Engine not Bound

### ISSUE THREAD

**Issue by copperspeed** [dlutton/flutter_tts#11]
I am receiving the following error : W/TextToSpeech( 8234): speak failed: not bound to TTS engine.

Do you know how to resolve it?

**Comment by dlutton** [comment]
I'm not sure the platform you're using, however I was able to recreate the issue on Android with the example.  I moved the getLanuages outside of the initTts since it was trying to get the list of languages prior to Android initializing Text to Speech.

I updated the example to reflect that.  Hopefully this helps, if not then please provide additional information.

**Comment by copperspeed** [comment]
Thanks for the updates, but I am still receiving the same error in the console with no sound.

`W/TextToSpeech(15825): speak failed: not bound to TTS engine
W/TextToSpeech(15825): stop failed: not bound to TTS engine
W/TextToSpeech(15825): speak failed: not bound to TTS engine
W/TextToSpeech(15825): stop failed: not bound to TTS engine`

I am using your latest project changes with Android Pie emulated.

**Comment by dlutton** [comment]
I was able to recreate the error with Android Pie as well.  If you're using my example as a reference, remove `async` from the initTts() method and you shouldn't receive that error.  Ensure your speak and and stop is occurring after FlutterTts is instantiated.  The example I provided in this repo is definitely lacking.  Please let me know if this doesn't solve your issue.

**Comment by copperspeed** [comment]
Sorry, but it does not solve the issue.

**Comment by dlutton** [comment]
okay can you provide some more context or provide a snipped of your code since I'm not receiving the error with the example I provided once I removed async from initTts().
