### ISSUE TITLE
Hindi tts is not supported for windows application 

### ISSUE THREAD

**Issue by Prashant-108538-Soni** [dlutton/flutter_tts#427]
## 🐛 Bug Report

Hindi text to speech is not supported for windows application 

As Ii implemented flutter tts for windows application then it speak only English language but I need Hindi tts .

**Version: 3.8.3

**Platform:** 
- windows

**Comment by Prashant-108538-Soni** [comment]
@vagoston kindly look at this issue. I need hindi tts support for windows application.

**Comment by vagoston** [comment]
Hi @Prashant-108538-Soni,
First of all, flutter tts does not contain any languages or voices, just using what is provided by the OS.
Are you trying to create a win32 or a UWP application?
For windows 7+ using win32 is discouraged. The reason is that there are two sets of voices, one is for the old way of tts, that is used by win32 applications and it is very complicated, although not impossible, to install languages.
For UWP, you only need to install tts for hindi language. Once that's done, the flutter tts will work with Hindi language. 
Let me know if you need further support.

**Comment by Prashant-108538-Soni** [comment]
My OS is windows 10 ( 64 bit ) and i want to built win32 desktop application for  supporting all windows version above 8 ( win 8+) But I don't get Hindi Tts support in this. This application is for visually impaired student to learn Hindi keyboard so i need Hindi Tts and Client requirement is windows8+ not only windows10.

What is the solution I can try ??

If I make a UWP application then it support only windows10 version but i have to cover all version of windows above 8 with Hindi Tts support. This is my main concern

**Comment by vagoston** [comment]
Sorry, you are right, UWP is not going to work with Win 8.
OK, so if you want to use a 32 bit tts, it can only access the 32 bit (sapi5) voices.
https://www.youtube.com/watch?v=x4W2HhqXM9s contains details about how to add sapi5 voices to windows 10. It is somewhat easier to add these to windows 8, but that is still not something that flutter tts is responsible for.

**Comment by Prashant-108538-Soni** [comment]
@vagoston Thank you for your support , my issue is resolved now. I am facing this issue since last 1 month, thank you for your incredible support.
