### ISSUE TITLE
Flutter Tts Error Looking for missing header file

### ISSUE THREAD

**Issue by RayOkaah** [dlutton/flutter_tts#7]
Whenever I try to build my project, the build seems to complete and then throws this error and I'm stuck. I have searched all through the internet still haven't seen anything that works.

 Xcode's output:
` ↳  === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_tts-umbrella.h"`
            ^
    `/Users/User/myFlutterProjects/news/ios/Pods/Target Support Files/flutter_tts/flutter_tts-umbrella.h:13:9: note: in file included from /Users/User/myFlutterProjects/news/ios/Pods/Target Support Files/flutter_tts/flutter_tts-umbrella.h:13:
    #import "FlutterTtsPlugin.h"`
            ^
    /Users/User/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.0.7/ios/Classes/FlutterTtsPlugin.h:2:9: error: 'flutter_tts/flutter_tts-Swift.h' file not found
    #import <flutter_tts/flutter_tts-Swift.h>
            ^
    `<unknown>:0: error: could not build Objective-C module 'flutter_tts'
Could not build the application for the simulator.
Error launching application on iPhone X.`

I must add this is only specific to IOS. 
Everything works fine in android.

**Comment by dlutton** [comment]
When you created your project, did you create it with the -i swift command?  If not, there have been some known issues with adding swift packages to projects created with objective-c.

You can follow the below link to see if anything mentioned assist with your issue.
[flutter issue](https://github.com/flutter/flutter/issues/16049)

**Comment by dlutton** [comment]
When you first create your flutter project, you can create it with a swift flag such as `flutter create -i swift newProject`.  This flag will create the necessary swift and bridging header files inside your ios folder and also updates your podfile.  There are some other differences that I haven't looked at it.

If you try creating a new project with the -i swift flag and include any package built in swift, you shouldn't have any issues.

**Comment by Rockvole** [comment]
This is a general problem with flutter and not the fault of the tts plugin. I encountered a similar issue :

https://github.com/flutter/flutter/issues/20576

**Comment by RayOkaah** [comment]
@dlutton Cool. I do Create new projects via android Studio. But perhaps with this information I'll switch to command line.
Might start a new project and manually move all my files if all else doesnt work.
@RockVole Thanks.

**Comment by RayOkaah** [comment]
Just thought I should update with the outcome.

Ran `flutter create -i swift newProject` as suggested.  Copied my lib files and assets to the new project, and now it works like a happy baby. Thanks  a lot, and even more for the awesome plugin. 👌

**Comment by monggos** [comment]
how may i going to fix this error?? i been solving this for a week now but no luck!

my project created to support swift using command line and tried also using Android Studio.. result are the same..

i also tried different swift version 4, 4.2 and 5 

<img width="1591" alt="Screen Shot 2019-10-14 at 10 39 55 PM" src="https://user-images.githubusercontent.com/2043996/66759856-95c90480-eed3-11e9-8012-7a75a8aeb00c.png">


But using flutter build command line, i am able to deploy it on my actual device my iphone but when i am Archiving it using XCode that error above occurred..

<img width="787" alt="Screen Shot 2019-10-14 at 10 42 42 PM" src="https://user-images.githubusercontent.com/2043996/66760202-315a7500-eed4-11e9-9860-49848680111a.png">


I don't think that it is caused by the plugin.. i think the XCode cannot locate the plugin config or something..

**Comment by WaterHashira** [comment]
@monggos you can try `flutter clean` once it may help
