### ISSUE TITLE
setStartHandler/setCompletionHandler are not called

### ISSUE THREAD

**Issue by sashko** [dlutton/flutter_tts#71]
## 💬 Questions and Help

I have an app in which I am trying to [register callbacks](https://github.com/sashko/speak_nato/blob/master/lib/screens/main_screen.dart#L42) to start/stop speak with the appropriate methods, but neither of them is called.

Might be related to #53, but I could not get what the issue was in that case.

Any assistance would be highly appreciated. Thank you.

<pre>
  initTts() async {
    tts.setStartHandler(() {
      print(&quot;start&quot;);
      setState(() {
        ttsState = TtsState.playing;
      });
    });

    tts.setCompletionHandler(() {
      print(&quot;stop&quot;);
      setState(() {
        ttsState = TtsState.stopped;
      });
    });
</pre>

**Comment by dlutton** [comment]
@sashko I tested the registered callbacks again with the example in this repo and it's working.  Please test with the example provided and let me know if it's failing and the emulator devices you're testing with.

**Comment by sashko** [comment]
Example app works. I have basically copy-pasted code, and have no idea what I would be missing....

**Comment by dlutton** [comment]
I'm assuming it's because you're importing `package:speak_nato/preferences.dart` which is already instantiating FlutterTts.  Maybe try passing your instance from your main_screen.dart into the preferences.dart like getLanguage(tts) and your preferences.dart containing `Future<String> getLanguage(FlutterTts tts) async` so you can remove `var tts = new FlutterTts();`.

**Comment by dlutton** [comment]
Did my suggestion fix your issue @sashko ?

**Comment by sashko** [comment]
Apologizes for the delay - was away without my laptop.

You were right. Many thanks for your assistance!
