### ISSUE TITLE
initHandler is not called on Android in example

### ISSUE THREAD

**Issue by ertong** [dlutton/flutter_tts#75]
## 🐛 Bug Report

1. Run example.
2. Hot reload example.
3. Voices and languages are not loaded.

It looks like dart part of the library does not reflect the state of the android part.
In this case initHandler is not called, because android part is not hot reloaded and initialization is not done second time.

### Expected behavior

Hot reload should work.

**Version:** 0.7.0

**Platform:** 
Android

**Comment by dlutton** [comment]
That's correct @ertong, it doesn't work during a hot reload because of the flutterTts.ttsInitHandler since the android tts engine has already been initialized.  To correct that you can set a boolean variable and under the Platform.isAndroid, check to see if it has been initialized or not and if it's a true value, you just call the _getLanguages() method without the flutterTts.ttsInitHandler.  I will correct this in the example in my next update so it works with hot reload.

**Comment by ertong** [comment]
Maybe there is some sense to make API like 
flutterTts.onReady((){ ... })
regardless of iOS/Android and check all conditions in the library (and execute in-place if the library is already ready).

In addition it would be nice to add something like isReady flag.

**Comment by dlutton** [comment]
@ertong this is being addressed through #73 and now that I've added web support to this plugin, I'll need to ensure it works across both iOS/Android/Web.

**Comment by dlutton** [comment]
@ertong please test again when you have a moment.  You should no longer require the initHandler.

**Comment by dlutton** [comment]
closing as the initHandler is no longer used.
